// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/lyro41/currency-rate-service/internal/api"
)

type CurrencyRate struct {
	ID             uuid.UUID        `json:"id"`
	Pair           string           `json:"pair"`
	Status         api.RateStatus   `json:"status"`
	Rate           pgtype.Numeric   `json:"rate"`
	UpdateTime     pgtype.Timestamp `json:"update_time"`
	IdempotencyKey pgtype.Text      `json:"idempotency_key"`
}
