// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/lyro41/plata-go-assignment/internal/api"
)

type RateStatus string

const (
	RateStatusPending RateStatus = "pending"
	RateStatusFetched RateStatus = "fetched"
	RateStatusFailed  RateStatus = "failed"
)

func (e *RateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RateStatus(s)
	case string:
		*e = RateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RateStatus: %T", src)
	}
	return nil
}

type NullRateStatus struct {
	RateStatus RateStatus `json:"rate_status"`
	Valid      bool       `json:"valid"` // Valid is true if RateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RateStatus), nil
}

type CurrencyRate struct {
	ID         uuid.UUID      `json:"id"`
	Pair       string         `json:"pair"`
	Status     api.RateStatus `json:"status"`
	Rate       sql.NullString `json:"rate"`
	UpdateTime sql.NullTime   `json:"update_time"`
}
