// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/lyro41/plata-go-assignment/internal/api"
)

const createUpdateRequest = `-- name: CreateUpdateRequest :one
INSERT INTO currency_rates (id, pair, status)
VALUES ($1, $2, $3)
RETURNING id, pair
`

type CreateUpdateRequestParams struct {
	ID     uuid.UUID      `json:"id"`
	Pair   string         `json:"pair"`
	Status api.RateStatus `json:"status"`
}

type CreateUpdateRequestRow struct {
	ID   uuid.UUID `json:"id"`
	Pair string    `json:"pair"`
}

func (q *Queries) CreateUpdateRequest(ctx context.Context, arg CreateUpdateRequestParams) (CreateUpdateRequestRow, error) {
	row := q.db.QueryRow(ctx, createUpdateRequest, arg.ID, arg.Pair, arg.Status)
	var i CreateUpdateRequestRow
	err := row.Scan(&i.ID, &i.Pair)
	return i, err
}

const getCurrencyRate = `-- name: GetCurrencyRate :one
SELECT id, pair, status, rate, update_time FROM currency_rates
WHERE status = $1 AND pair = $2
ORDER BY update_time DESC
LIMIT 1
`

type GetCurrencyRateParams struct {
	Status api.RateStatus `json:"status"`
	Pair   string         `json:"pair"`
}

func (q *Queries) GetCurrencyRate(ctx context.Context, arg GetCurrencyRateParams) (CurrencyRate, error) {
	row := q.db.QueryRow(ctx, getCurrencyRate, arg.Status, arg.Pair)
	var i CurrencyRate
	err := row.Scan(
		&i.ID,
		&i.Pair,
		&i.Status,
		&i.Rate,
		&i.UpdateTime,
	)
	return i, err
}

const getCurrencyRateByID = `-- name: GetCurrencyRateByID :one
SELECT id, pair, status, rate, update_time FROM currency_rates
WHERE id = $1
`

func (q *Queries) GetCurrencyRateByID(ctx context.Context, id uuid.UUID) (CurrencyRate, error) {
	row := q.db.QueryRow(ctx, getCurrencyRateByID, id)
	var i CurrencyRate
	err := row.Scan(
		&i.ID,
		&i.Pair,
		&i.Status,
		&i.Rate,
		&i.UpdateTime,
	)
	return i, err
}

const updateCurrencyRate = `-- name: UpdateCurrencyRate :exec
UPDATE currency_rates
SET status = $2, rate = $3, update_time = $4
WHERE id = $1
`

type UpdateCurrencyRateParams struct {
	ID         uuid.UUID        `json:"id"`
	Status     api.RateStatus   `json:"status"`
	Rate       pgtype.Numeric   `json:"rate"`
	UpdateTime pgtype.Timestamp `json:"update_time"`
}

func (q *Queries) UpdateCurrencyRate(ctx context.Context, arg UpdateCurrencyRateParams) error {
	_, err := q.db.Exec(ctx, updateCurrencyRate,
		arg.ID,
		arg.Status,
		arg.Rate,
		arg.UpdateTime,
	)
	return err
}
